name: Noetic CI

on:
  push:
    branches:
      - 'noetic'
  pull_request:
    branches:
      - 'noetic'
  workflow_dispatch:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker setup and build
        run: docker build . -t mesh_nav/noetic -f ci/Dockerfile-noetic
      - name: catkin lint
        run: docker run mesh_nav/noetic catkin_lint src
